version: "3"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - $DB_PORT:3306